%clear; clc; close all; %
function total_avg_power = WFSim_simulation_use(yaw_angles)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%
    %%      WIND FARM SIMULATOR (WFSIM) by S. Boersma and B. Doekemeijer
    %                 Delft University of Technology, 2018
    %          Repo: https://github.com/TUDelft-DataDrivenControl/WFSim
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %% Define simulation settings: layout, control inputs and simulation duration
    wfsim_dir = fileparts(mfilename('fullpath'));
    addpath(fullfile(wfsim_dir, 'layoutDefinitions')); 
    addpath(fullfile(wfsim_dir, 'controlDefinitions')); 
    addpath(fullfile(wfsim_dir, 'solverDefinitions')); 
    
    Wp = layoutSet_sowfa_9turb_apc_alm_turbl(); 
    turbInputSet = controlSet_sowfa_9turb_apc_alm_turbl(Wp); 
    modelOptions = solverSet_default(Wp); 
    
    NN = floor(turbInputSet.t(end)/Wp.sim.h); 
    
    verboseOptions.printProgress = 0;    
    verboseOptions.Animate       = 0;   
    verboseOptions.plotMesh      = 0;    
    
    %% Script core functions
    run('WFSim_addpaths.m');                    
    [Wp,sol,sys] = InitWFSim(Wp,modelOptions,verboseOptions.plotMesh); 
    
    CPUTime   = []; 
    if verboseOptions.Animate > 0 
        hfig = figure('color',[0 166/255 214/255],'units','normalized',...
            'outerposition',[0 0 1 1],'ToolBar','none','visible', 'on');
    end
    
    NN = 100; % Number of simulations
    
    turbInputSet.phi = zeros(Wp.turbine.N, NN + 1); 
    turbInputSet.CT_prime = turbInputSet.CT_prime(:, 1:(NN+1));
    turbInputSet.t = 0:NN;
    
    % Initialize array to track total power over time
    total_power_history = zeros(1, NN);
    
    % Initialising yaw (phi)
    turbInputSet.phi = zeros(Wp.turbine.N, NN+1);
    
    % Ensure yaw_angles is treated as double
    yaw_angles = double(yaw_angles);
    disp(['Simulating with yaw angle: ', num2str(yaw_angles)]);
    turbInputSet.phi(1:Wp.turbine.N, :) = yaw_angles;
    
    % Performing forward time propagations
    disp(['Performing ' num2str(NN) ' forward simulations..']);
    while sol.k < NN
        tic;                    
        
        turbInput = struct('t',sol.time);
        for i = 1:Wp.turbine.N
            turbInput.CT_prime(i,1) = interp1(turbInputSet.t,turbInputSet.CT_prime(i,:),sol.time,turbInputSet.interpMethod);
            turbInput.phi(i,1)      = interp1(turbInputSet.t,turbInputSet.phi(i,:),     sol.time,turbInputSet.interpMethod);
        end
        
        [sol,sys]      = WFSim_timestepping(sol,sys,Wp,turbInput,modelOptions); 
        CPUTime(sol.k) = toc;   
        
        % Save sol to cell array
        sol_array(sol.k) = sol; 
        
        % Track the total power generated by all turbines at this timestep
        total_power_history(sol.k) = sum(sol.turbine.power);
    
        if verboseOptions.printProgress
           disp(['Simulated t(' num2str(sol.k) ') = ' num2str(sol.time) ...
                  ' s. CPU: ' num2str(CPUTime(sol.k)*1e3,3) ' ms.' ...
                  ' Total Power Output: ' num2str(sum(sol.turbine.power)) ' W']);
        end
        
        if verboseOptions.Animate > 0
            if ~rem(sol.k,verboseOptions.Animate)
                hfig = WFSim_animation(Wp,sol,hfig); 
            end
        end
    end
    disp(' ')
    disp(['Completed ' num2str(NN) ' forward simulations. Average CPU time: ' num2str(mean(CPUTime)*10^3,3) ' ms.']);
    
    % Return the true average power output starting from timestep 36
    % This ignores the first 35 timesteps while wakes propagate
    if NN >= 36
        total_avg_power = mean(total_power_history(36:end));
    else
        total_avg_power = mean(total_power_history); % Fallback if NN < 36
    end
    
    disp(['Average Power Output (Timestep 36 to End): ' num2str(total_avg_power) ' W']);
end
