%clear; clc; close all; %
function total_avg_power = WFSim_simulation_use(yaw_angles)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%
    %%      WIND FARM SIMULATOR (WFSIM) by S. Boersma and B. Doekemeijer
    %                 Delft University of Technology, 2018
    %          Repo: https://github.com/TUDelft-DataDrivenControl/WFSim
    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %% Define simulation settings: layout, control inputs and simulation duration
    wfsim_dir = fileparts(mfilename('fullpath'));
    addpath(fullfile(wfsim_dir, 'layoutDefinitions')); 
    addpath(fullfile(wfsim_dir, 'controlDefinitions')); 
    addpath(fullfile(wfsim_dir, 'solverDefinitions')); 
    
    Wp = layoutSet_sowfa_9turb_apc_alm_turbl(); 
    
    % UPDATED: Using the greedy control set instead of sowfa_9turb_apc_alm_turbl
    turbInputSet = controlSet_greedy(Wp); 
    
    modelOptions = solverSet_default(Wp); 
    
    NN = floor(turbInputSet.t(end)/Wp.sim.h); 
    
    verboseOptions.printProgress = 0;    
    verboseOptions.Animate       = 0;   
    verboseOptions.plotMesh      = 0;    
    
    %% Script core functions
    run('WFSim_addpaths.m');                    
    [Wp,sol,sys] = InitWFSim(Wp,modelOptions,verboseOptions.plotMesh); 
    
    CPUTime   = []; 
    if verboseOptions.Animate > 0 
        hfig = figure('color',[0 166/255 214/255],'units','normalized',...
            'outerposition',[0 0 1 1],'ToolBar','none','visible', 'on');
    end
    
    NN = 998; % Number of simulations
    
    % Ensure turbInputSet matrices are sized correctly 
    turbInputSet.phi = zeros(Wp.turbine.N, NN + 1); 
    
    % Pad or truncate CT_prime to match NN
    if size(turbInputSet.CT_prime, 2) < NN + 1
        % Pad with the last value if too short
        turbInputSet.CT_prime = [turbInputSet.CT_prime, repmat(turbInputSet.CT_prime(:,end), 1, (NN+1) - size(turbInputSet.CT_prime, 2))];
    else
        turbInputSet.CT_prime = turbInputSet.CT_prime(:, 1:(NN+1));
    end
    
    turbInputSet.t = 0:NN;
    
    % Initialize array to track total power over time
    total_power_history = zeros(1, NN);
    
    % Ensure yaw_angles is treated as double
    yaw_angles = double(yaw_angles);
    disp(['Simulating with yaw angle: ', num2str(yaw_angles)]);
    turbInputSet.phi(1:Wp.turbine.N, :) = yaw_angles;
    
    % Performing forward time propagations inside a try-catch for safety
    disp(['Performing ' num2str(NN) ' forward simulations..']);
    
    try
        while sol.k < NN
            tic;                    
            
            turbInput = struct('t',sol.time);
            for i = 1:Wp.turbine.N
                turbInput.CT_prime(i,1) = interp1(turbInputSet.t,turbInputSet.CT_prime(i,:),sol.time,turbInputSet.interpMethod);
                turbInput.phi(i,1)      = interp1(turbInputSet.t,turbInputSet.phi(i,:),     sol.time,turbInputSet.interpMethod);
            end
            
            [sol,sys]      = WFSim_timestepping(sol,sys,Wp,turbInput,modelOptions); 
            CPUTime(sol.k) = toc;   
            
            % Track the total power generated by all turbines at this timestep
            total_power_history(sol.k) = sum(sol.turbine.power);
        
            if verboseOptions.printProgress
               disp(['Simulated t(' num2str(sol.k) ') = ' num2str(sol.time) ...
                      ' s. CPU: ' num2str(CPUTime(sol.k)*1e3,3) ' ms.' ...
                      ' Total Power Output: ' num2str(sum(sol.turbine.power)) ' W']);
            end
            
            if verboseOptions.Animate > 0
                if ~rem(sol.k,verboseOptions.Animate)
                    hfig = WFSim_animation(Wp,sol,hfig); 
                end
            end
        end
        disp(' ')
        disp(['Completed ' num2str(NN) ' forward simulations. Average CPU time: ' num2str(mean(CPUTime)*10^3,3) ' ms.']);
        
        % Return the true average power output starting from timestep 100
        total_avg_power = mean(total_power_history(100:end));
        
        % Extra safeguard against simulator returning NaN or Inf output 
        if isnan(total_avg_power) || isinf(total_avg_power)
            disp('Simulation returned NaN or Inf. Applying penalty.');
            total_avg_power = -1e9;
        end
        
        disp(['Average Power Output (Timestep 100 to End): ' num2str(total_avg_power) ' W']);

    catch ME
        % If WFSim crashes (e.g. at -30 yaw), catch it here and heavily penalize
        disp('===================================================');
        disp(['SIMULATION CRASHED for yaw angle: ', num2str(yaw_angles)]);
        disp(['Error Message: ', ME.message]);
        disp('Safely returning penalized value to optimizer.');
        disp('===================================================');
        
        total_avg_power = -1e9;
    end
end
